theme: jekyll-theme-minimal
title: Kallil de Araújo Bezerra
description: I am a computer engineer but my professinal experience is towards Data Analysis and Business Intelligence.
logo: https://avatars1.githubusercontent.com/u/15151896?s=460&v=4
